= Soft Assertions - demo
:toc:
:toc-placement:
:toclevels: 3
:icons: font
:note-caption: :information_source:

== Introduction

Given it's the advent of a new year, I thought let's start with something nice and fun that can make live more enjoyable for everyone.

As developers, we write testcases all the time to help us in our development process, and to help us detect potential regressions in the future.

Now ideally we want our testcases to be as efficient as possible, and ideally to require as few reruns as possible. And this is where Soft Assertions come into play.

== Hard Assertions vs Soft Assertions

=== "Hard" assertion

These are the traditional assertions that everyone's used to seeing, we assert field by field, and halt as soon as one assertion fails. Hence, "hard" assertions.

For example

[code,java]
----
assertEquals(person1.getName(), personRecord1.name());
assertEquals(person1.getMainLanguage(), personRecord1.mainLanguage());
assertEquals(person1.getEmail(), personRecord1.email());
assertEquals(person1.getAddress(), personRecord1.address());
assertEquals(person1.getPhoneNumber(), personRecord1.phoneNumber());
assertEquals(person1.getDateOfBirth().toString(), personRecord1.dateOfBirth());
----

If, for example, our e-mail assertion were to fail we would receive no information on the validity of the address, phone number or date of birth.

Or even earlier, if our main language was wrong we'd just receive something like:

[code]
----
org.opentest4j.AssertionFailedError:
Expected :French
Actual   :English
----

=== "Soft" assertion

With soft assertions we bundle our assertions, run them internally and then output all possible failures.
All our assertions will be executed.

You can set up something for this yourself, or certain libraries also handle this for you as we'll cover later.


=== So when should we use them?

Ideally when you're performing more than one assertion on the same object.
I dislike flaky tests, and having to run the same test multiple times just to figure out what's wrong with for example the mapping of a single object.


== Library support

Some of the most commonly used Assertion libraries have out of the box support for soft assertions, sadly, not all of them do.

[cols="1,1"]
|===
|Framework|Supported
| JUnit | [x]
| AssertJ | [x]
| Hamcrest | [ ]
| TestNG | [x]
| Truth | [ ]
|===

As of the moment of writing Truth does have an open pull request for this, but it's been in that state for a couple of years.

TIP: In case you know of another library that supports soft assertions, please do let me know and I'll add it to this list.

TIP: To focus more on the functionality itself the testcase is very basic. We're testing the mapper, and mapping 2 objects. Let's say we're a smidge sleep deprived, and just copied the first assertions rather than extracting them to a method, and forgot to replace some references. With hard assertions we would get a failure on each individual error.


=== Junit

=== AssertJ

=== TestNG

== Takeaway

== References

* https://github.com/SimonVerhoeven/soft-assertions[This repository]
* https://junit.org/junit5/[JUnit]
* https://github.com/assertj/assertj[AssertJ]
* https://github.com/hamcrest/JavaHamcrest[Hamcrest]
* https://testng.org/[TestNG]
* https://truth.dev/[Truth]
