= Soft Assertions - demo
:toc:
:toc-placement:
:toclevels: 3
:icons: font
:note-caption: :information_source:

== Introduction

Given it's the advent of a new year, I thought let's start with something nice and fun that can make live more enjoyable for everyone.

As developers, we write testcases all the time to help us in our development process, and to help us detect potential regressions in the future.

Now ideally we want our testcases to be as efficient as possible, and ideally to require as few reruns as possible. And this is where Soft Assertions come into play.

== Hard Assertions vs Soft Assertions

=== "Hard" assertion

These are the traditional assertions that everyone's used to seeing, we assert field by field, and halt as soon as one assertion fails. Hence, "hard" assertions.

For example

[code,java]
----
assertEquals(person1.getName(), personRecord1.name());
assertEquals(person1.getMainLanguage(), personRecord1.mainLanguage());
assertEquals(person1.getEmail(), personRecord1.email());
assertEquals(person1.getAddress(), personRecord1.address());
assertEquals(person1.getPhoneNumber(), personRecord1.phoneNumber());
assertEquals(person1.getDateOfBirth().toString(), personRecord1.dateOfBirth());
----

If, for example, our e-mail assertion were to fail we would receive no information on the validity of the address, phone number or date of birth.

Or even earlier, if our main language was wrong we'd just receive something like:

[code]
----
org.opentest4j.AssertionFailedError:
Expected :French
Actual   :English
----

=== "Soft" assertion

With soft assertions we bundle our assertions, run them internally and then output all possible failures.
All our assertions will be executed.

You can set up something for this yourself, or certain libraries also handle this for you as we'll cover later.


== Library support

Some of the most commonly used Assertion libraries have out of the box support for soft assertions, sadly, not all of them do.

[cols="1,1"]
|===
|Framework|Supported
| JUnit | [x]
| AssertJ | [x]
| Hamcrest | [ ]
| TestNG | [x]
| Truth | [ ]
|===

=== Junit

=== AssertJ

=== TestNG

== Takeaway

== References

* https://github.com/SimonVerhoeven/soft-assertions[This repository]
